.PHONY: clean All

All:
	@echo "----------Building project:[ SelectionSort - Debug ]----------"
	@cd "SelectionSort" && "$(MAKE)" -f  "SelectionSort.mk"
clean:
	@echo "----------Cleaning project:[ SelectionSort - Debug ]----------"
	@cd "SelectionSort" && "$(MAKE)" -f  "SelectionSort.mk" clean
